on: push

jobs:
  check:
    name: "Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: 'Install Dependencies'
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --system --dev
      - name: 'Check Formatting (flake8)'
        run: flake8 nessclient examples nessclient_tests docs
      - name: 'Check Formatting (black)'
        run: black --check nessclient examples nessclient_tests docs
      - name: 'Check Types'
        run: python3 -m mypy --strict nessclient examples nessclient_tests docs
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: 'Install Dependencies'
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv wheel
          pipenv install --system --dev

      - name: 'Run Tests (with coverage)'
        run: |
          coverage run -m pytest  && coverage html && coverage report --omit=setup.py --omit=.eggs
      - uses: codecov/codecov-action@v2
        if: ${{ matrix.python-version == '3.x' }}

      - name: "Build"
        run: |
          sed -i "s/0.0.0-dev/$(git describe --tags --exact-match)/" nessclient/__init__.py
          python -m build
      # - uses: actions/upload-artifact@v2
      #   # Only publish artifacts from Python latest build.
      #   if: ${{ matrix.python-version == '3.x' }}
      #   with:
      #     name: dist
      #     path: dist/
      #     if-no-files-found: error
